import type { GisPoint } from '@/entities/gis-point/types';
import type { Photo } from '@/entities/photo/types';

export type NetworkType = 'ОТ' | 'ГВС';
export type DamageType = 'Текущее' | 'Гидравлическое';
export type OrderKind = 'Текущий' | 'Гарантийный';
export type AreaState = 'В РАБОТЕ' | 'ГОТОВ К ЗАКРЫТИЮ';
export type ContractorType = 'Подрядчик' | 'УРТС' | 'Участок';

export type Damage = {
  id: string;
  districtId: string;
  address: string;
  networkType: NetworkType;
  detectedAt: string;
  fixedAt: string | null;
  orderNumber: string;
  orderOpenedAt: string | null;
  orderValidUntil: string | null;
  heatSource: string;
  damageType: DamageType;
  disconnectedAddresses: string;
  damageDescription: string;
  orderKind: OrderKind | null;
  greenZoneArea: number;
  asphaltArea: number;
  improvementMain: boolean;
  improvementInnerRoad: boolean;
  improvementSidewalk: boolean;
  improvementBlindArea: boolean;
  curbCount: number;
  areaState: AreaState;
  contractorType: ContractorType;
  contractNumber: string;
  contractorRequestDate: string | null;
  plannedFinishDate: string | null;
  note: string;
  orderClosedAt: string | null;
  gisPoint: GisPoint | null;
  photos: Photo[];
  createdAt: string;
  updatedAt: string;
  archived: boolean;
};
