# Generated by Django 6.0.5 on 2026-05-22 10:31

import apps.incidents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('id', models.CharField(default=apps.incidents.models.generate_damage_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=512)),
                ('network_type', models.CharField(choices=[('ОТ', 'ОТ'), ('ГВС', 'ГВС')], max_length=8)),
                ('detected_at', models.DateField()),
                ('fixed_at', models.DateField(blank=True, null=True)),
                ('order_number', models.CharField(max_length=64)),
                ('order_opened_at', models.DateField()),
                ('order_valid_until', models.DateField()),
                ('heat_source', models.CharField(max_length=512)),
                ('damage_type', models.CharField(choices=[('Текущее', 'Текущее'), ('Гидравлическое', 'Гидравлическое')], max_length=32)),
                ('disconnected_consumers', models.IntegerField(default=0)),
                ('damage_description', models.TextField()),
                ('order_kind', models.CharField(choices=[('Текущий', 'Текущий'), ('Гарантийный', 'Гарантийный')], max_length=32)),
                ('green_zone_area', models.IntegerField(default=0)),
                ('asphalt_area', models.IntegerField(default=0)),
                ('improvement_main', models.BooleanField(default=False)),
                ('improvement_inner_road', models.BooleanField(default=False)),
                ('improvement_sidewalk', models.BooleanField(default=False)),
                ('improvement_blind_area', models.BooleanField(default=False)),
                ('curb_count', models.IntegerField(default=0)),
                ('area_state', models.CharField(choices=[('В РАБОТЕ', 'В РАБОТЕ'), ('ГОТОВ К ЗАКРЫТИЮ', 'ГОТОВ К ЗАКРЫТИЮ')], max_length=32)),
                ('contractor_type', models.CharField(choices=[('Подрядчик', 'Подрядчик'), ('УРТС', 'УРТС'), ('Участок', 'Участок')], max_length=32)),
                ('contractor_name', models.CharField(blank=True, default='', max_length=255)),
                ('contract_number', models.CharField(blank=True, max_length=128)),
                ('contractor_request_date', models.DateField(blank=True, null=True)),
                ('planned_finish_date', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('order_closed_at', models.DateField(blank=True, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='damages', to='accounts.district')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GisPoint',
            fields=[
                ('id', models.CharField(default=apps.incidents.models.generate_gis_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=512)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('gis_object_id', models.CharField(max_length=128)),
                ('map_url', models.URLField(blank=True, max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('damage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gis_point', to='incidents.damage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.CharField(default=apps.incidents.models.generate_photo_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=1024)),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('damage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='incidents.damage')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.CharField(default=apps.incidents.models.generate_audit_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=64)),
                ('entity_id', models.CharField(max_length=64)),
                ('user_name', models.CharField(max_length=255)),
                ('field_name', models.CharField(max_length=128)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='incidents_a_entity__473c47_idx')],
            },
        ),
    ]
