# Generated by Django 6.0.7 on 2026-07-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='url',
        ),
        migrations.AddField(
            model_name='photo',
            name='file',
            field=models.FileField(default='', upload_to='damage_photos/%Y/%m/'),
            preserve_default=False,
        ),
    ]
