# Generated by Django 6.0.7 on 2026-08-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_remove_photo_url_photo_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='damage',
            name='disconnected_consumers',
        ),
        migrations.AddField(
            model_name='damage',
            name='disconnected_addresses',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='damage',
            name='order_kind',
            field=models.CharField(blank=True, choices=[('Текущий', 'Текущий'), ('Гарантийный', 'Гарантийный')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='damage',
            name='order_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='damage',
            name='order_opened_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='damage',
            name='order_valid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
