# Generated by Django 6.0.8 on 2026-09-01 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_remove_damage_disconnected_consumers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='damage',
            name='contractor_name',
        ),
    ]
