import type { AuditEvent, Damage, Order, User } from '@/entities';

const now = new Date().toISOString();

export const mockUsers: User[] = [
  {
    id: 'u-admin',
    ldapLogin: 'admin',
    fullName: 'Администратор системы',
    role: 'admin',
    districtId: null,
    isActive: true,
    lastLoginAt: now,
  },
  {
    id: 'u-damage',
    ldapLogin: 'ivanov',
    fullName: 'Иванов Сергей Петрович',
    role: 'district_damage',
    districtId: 'central',
    isActive: true,
    lastLoginAt: now,
  },
  {
    id: 'u-oopppr',
    ldapLogin: 'oopppr',
    fullName: 'Петрова Анна Игоревна',
    role: 'oopppr',
    districtId: null,
    isActive: true,
    lastLoginAt: now,
  },
];

export const mockDamages: Damage[] = [
  {
    id: 'd-1001',
    districtId: 'central',
    address: 'ул. Ленина, 12',
    networkType: 'ОТ',
    detectedAt: '2026-05-11',
    fixedAt: null,
    orderNumber: 'ОР-2026-0012',
    orderOpenedAt: '2026-05-11',
    orderValidUntil: '2026-06-10',
    heatSource: 'ТЭЦ-3',
    damageType: 'Текущее',
    disconnectedAddresses: 'ул. Ленина, 10, 14',
    damageDescription: 'Повреждение подающего трубопровода',
    orderKind: 'Текущий',
    greenZoneArea: 12,
    asphaltArea: 8,
    improvementMain: true,
    improvementInnerRoad: false,
    improvementSidewalk: true,
    improvementBlindArea: false,
    curbCount: 3,
    areaState: 'В РАБОТЕ',
    contractorType: 'Подрядчик',
    contractNumber: 'Д-44/26',
    contractorRequestDate: '2026-05-12',
    plannedFinishDate: '2026-05-28',
    note: 'Контроль восстановления покрытия',
    orderClosedAt: null,
    gisPoint: {
      id: 'gp-1',
      address: 'ул. Ленина, 12',
      latitude: 54.6292,
      longitude: 39.7364,
      gisObjectId: 'GIS-001',
      mapUrl: 'https://maps.example.local/GIS-001',
    },
    photos: [{ id: 'p-1', url: '#', fileName: 'damage.jpg', uploadedAt: now }],
    createdAt: now,
    updatedAt: now,
    archived: false,
  },
  {
    id: 'd-1002',
    districtId: 'north',
    address: 'пр. Мира, 78',
    networkType: 'ГВС',
    detectedAt: '2026-05-15',
    fixedAt: '2026-05-17',
    orderNumber: 'ОР-2026-0031',
    orderOpenedAt: '2026-05-15',
    orderValidUntil: '2026-06-14',
    heatSource: 'Котельная Северная',
    damageType: 'Гидравлическое',
    disconnectedAddresses: '',
    damageDescription: 'Повреждение после испытаний',
    orderKind: 'Гарантийный',
    greenZoneArea: 0,
    asphaltArea: 18,
    improvementMain: true,
    improvementInnerRoad: true,
    improvementSidewalk: false,
    improvementBlindArea: false,
    curbCount: 0,
    areaState: 'ГОТОВ К ЗАКРЫТИЮ',
    contractorType: 'УРТС',
    contractNumber: '',
    contractorRequestDate: null,
    plannedFinishDate: '2026-05-25',
    note: '',
    orderClosedAt: null,
    gisPoint: null,
    photos: [],
    createdAt: now,
    updatedAt: now,
    archived: false,
  },
];

export const mockOrders: Order[] = mockDamages.map((damage) => ({
  id: `o-${damage.id}`,
  districtId: damage.districtId,
  orderNumber: damage.orderNumber,
  address: damage.address,
  orderKind: damage.orderKind,
  openedAt: damage.orderOpenedAt,
  validUntil: damage.orderValidUntil,
  closedAt: damage.orderClosedAt,
  greenZoneArea: damage.greenZoneArea,
  asphaltArea: damage.asphaltArea,
  improvementMain: damage.improvementMain,
  improvementInnerRoad: damage.improvementInnerRoad,
  improvementSidewalk: damage.improvementSidewalk,
  improvementBlindArea: damage.improvementBlindArea,
  curbCount: damage.curbCount,
  areaState: damage.areaState,
  contractorType: damage.contractorType,
  contractNumber: damage.contractNumber,
  contractorRequestDate: damage.contractorRequestDate,
  plannedFinishDate: damage.plannedFinishDate,
  note: damage.note,
  gisPoint: damage.gisPoint,
  photos: damage.photos,
  archived: damage.archived,
  createdAt: damage.createdAt,
  updatedAt: damage.updatedAt,
}));

export const mockAudit: AuditEvent[] = [
  {
    id: 'a-1',
    entityType: 'damage',
    entityId: 'd-1001',
    userId: 'u-admin',
    userName: 'Администратор системы',
    fieldName: 'areaState',
    oldValue: 'В РАБОТЕ',
    newValue: 'ГОТОВ К ЗАКРЫТИЮ',
    createdAt: now,
  },
];
